import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body 
      className="min-h-dvh w-full flex flex-row"
      >
        <Navbar />
        <main
          className="flex flex-col justify-start items-center min-h-dvh px-20 py-17 bg-neutral-100"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
